### ISSUE TITLE
Fails to build with llvm 20.1 with the same errors

### ISSUE THREAD

**Issue by Boria138** [intel/opencl-clang#569]
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:65:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    65 | OPTION(prefix_1, "-D", D, JoinedOrSeparate, INVALID, INVALID, nullptr, 0, DefaultVis, 0, nullptr, (std::array<std::pair<std::array<unsigned, 2>, const char*>, 1>{{ std::make_pair(std::array<unsigned, 2>{{0, 0}}, nullptr) }}), nullptr, nullptr)
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:66:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    66 | OPTION(prefix_1, "-gline-tables-only", gline_tables_only_Flag, Flag, INVALID, INVALID, nullptr, 0, DefaultVis, 0, nullptr, (std::array<std::pair<std::array<unsigned, 2>, const char*>, 1>{{ std::make_pair(std::array<unsigned, 2>{{0, 0}}, nullptr) }}), nullptr, nullptr)
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:67:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    67 | OPTION(prefix_1, "-g", g_Flag, Flag, INVALID, INVALID, nullptr, 0, DefaultVis, 0,
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:69:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    69 | OPTION(prefix_1, "-I", I, JoinedOrSeparate, INVALID, INVALID, nullptr, RenderJoined, DefaultVis, 0,
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:71:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    71 | OPTION(prefix_1, "-profiling", profiling, Flag, INVALID, INVALID, nullptr, 0, DefaultVis, 0,
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:73:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    73 | OPTION(prefix_1, "-spir-std=1.0", spir_std_1_0, Flag, INVALID, INVALID, nullptr, 0, DefaultVis, 0, nullptr, (std::array<std::pair<std::array<unsigned, 2>, const char*>, 1>{{ std::make_pair(std::array<unsigned, 2>{{0, 0}}, nullptr) }}), nullptr, nullptr)
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:74:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    74 | OPTION(prefix_1, "-spir-std=1.2", spir_std_1_2, Flag, INVALID, INVALID, nullptr, 0, DefaultVis, 0, nullptr, (std::array<std::pair<std::array<unsigned, 2>, const char*>, 1>{{ std::make_pair(std::array<unsigned, 2>{{0, 0}}, nullptr) }}), nullptr, nullptr)
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:75:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    75 | OPTION(prefix_1, "-s", s, Separate, INVALID, INVALID, nullptr, 0, DefaultVis, 0, nullptr, (std::array<std::pair<std::array<unsigned, 2>, const char*>, 1>{{ std::make_pair(std::array<unsigned, 2>{{0, 0}}, nullptr) }}), nullptr, nullptr)
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:76:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    76 | OPTION(prefix_1, "-target-triple", target_triple, Separate, INVALID, INVALID, nullptr, 0, DefaultVis, 0,
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:78:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    78 | OPTION(prefix_1, "-triple", triple, Separate, INVALID, INVALID, nullptr, 0, DefaultVis, 0,
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/x86_64-alt-linux/opencl_clang_options.inc:80:8: error: 'prefix_1' was not declared in this scope
[00:00:09]    80 | OPTION(prefix_1, "-Werror", Werror, Flag, INVALID, INVALID, nullptr, 0, DefaultVis, 0, nullptr, (std::array<std::pair<std::array<unsigned, 2>, const char*>, 1>{{ std::make_pair(std::array<unsigned, 2>{{0, 0}}, nullptr) }}), nullptr, nullptr)
[00:00:09]       |        ^~~~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl-clang-20.1.0/options_compile.cpp:43:4: note: in definition of macro 'OPTION'
[00:00:09]    43 |   {PREFIX,                                                                     \
[00:00:09]       |    ^~~~~~
[00:00:09] /usr/src/RPM/BUILD/libintel-opencl
